removed Werror from CMakeList
UnityFail and UnityIgnore because noreturn function does return

/github/workspace/wge/src/unity/src/unity.c: In function ‘UnityFail’:
/github/workspace/wge/src/unity/src/unity.c:1792:1: error: ‘noreturn’ function does return [-Werror]
 1792 | }
      | ^
/github/workspace/wge/src/unity/src/unity.c: In function ‘UnityIgnore’:
/github/workspace/wge/src/unity/src/unity.c:1808:1: error: ‘noreturn’ function does return [-Werror]
 1808 | }
      | ^